name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          DJANGO_ENV: test
        run: docker-compose --file docker-compose.ci.yml run api make test

      - name: Copy coverage report from Docker container
        run: |
          CONTAINER_ID=$(docker ps -aqf "name=api")
          docker cp $CONTAINER_ID:/app/coverage.xml coverage.xml

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: cobertura
